config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root to: "main#index"
  get 'bacarratt'     => 'static_pages#bacarratt'
  get 'black_jack'    => 'static_pages#black_jack'
  get 'complites'     => 'static_pages#complites'
  get 'roulette'      => 'atatic_pages#roulette'
  get 'russian_poker' => 'static_pages#russian_poker'
  get 'texas_holdem'  => 'static_pages#texas_holdem'
  get 'main'          => 'main#home'
  get 'select'        => 'static_pages#select'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  #before_action  :authenticate_user!

  def select
  end

  def random
    rand(55..995).step(5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Предфильтры

    # Подтверждает вход пользователя
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Подтверждает администратора.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MathTesting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'bootstrap',  media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style',  media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'main',  media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <!--header-->
    <%= render 'static_pages/header' %>
    <!--header-->
    <div class="container">
    <%= yield %>
    </div>
    </div>
    <!--footer-->
    <br /><br /><%= render 'static_pages/footer' %>
    <!--footer-->

  </body>
</html>

app/views/main/home.html.erb
<h1>Home page</h1>

app/views/main/index.html.erb
<div class="center jumbotron" style="text-align: center;">
  <h2><b>Welcome to the Casino testing application</b></h2>

  <h4>
    First - you must to Sign-up and then lets start!
  </h4>
  <%= link_to "Sign up now!", class: "btn btn-lg btn-primary" %>
</div>
<div class="main-img">
  <%= link_to image_tag("1.jpg", alt: "Casino logo") %>
</div>

app/views/static_pages/_footer.html.erb
<div class="information">
  <div class="container">
    <div class="infor-top">
      <div class="col-md-3 infor-left">
        <h3>Follow us</h3>
        <ul>
          <li><a href="#"><span class="fb"></span><h6>Facebook</h6></a></li>
          <li><a href="#"><span class="twit"></span><h6>Twitter</h6></a></li>
          <li><a href="#"><span class="google"></span><h6>Google+</h6></a></li>
        </ul>
      </div>
      <div class="col-md-3 infor-left">
        <h3>Information</h3>
        <ul>
          <li><a href="#"><p>Specials</p></a></li>
          <li><a href="#"><p>New products</p></a></li>
          <li><a href="#"><p>Our Stores</p></a></li>
          <li><a href="contact.html"><p>Contact us</p></a></li>
          <li><a href="#"><p>Top Sellers</p></a></li>
        </ul>
      </div>
      <div class="col-md-3 infor-left">
        <h3>My Account</h3>
        <ul>
          <li><a href="account.html"><p>My Account</p></a></li>
          <li><a href="#"><p>My Credit slips</p></a></li>
          <li><a href="#"><p>My Merchandise returns</p></a></li>
          <li><a href="#"><p>My personal info</p></a></li>
          <li><a href="#"><p>My Addresses</p></a></li>
        </ul>
      </div>
      <div class="col-md-3 infor-left">
        <h3>Store Information</h3>
        <h4>The company name,
          <span>Lorem ipsum dolor,</span>
          Glasgow Dr 40 Fe 72</h4>
          <h5>+955 123 4567</h5>
          <p><a href="mailto:example@email.com">contact@example.com</a></p>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<!--information-end -->
<!--footer-starts -->
<div class="footer">
  <div class="container">
    <div class="footer-top">
      <div class="col-md-6 footer-left">
        <form>
          <input type="text" value="Enter Your Email" onfocus="this.value = '';"
          onblur="if (this.value == ''){this.value = 'Enter Your Email';}">
          <input type="submit" value="Subscribe">
        </form>
      </div>
      <div class="col-md-6 footer-right">
        <p>2019 Luxury Watches. All Rights Reserved</p>
      </div>
     <div class="clearfix"></div>
    </div>
  </div>
</div>

<!--modal -->
<div class="modal fade" id="cart" tabindex="-1" role="dialog" aria-labelledby="MyModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true">*</span></button>
        <h4 class="modal-title" id="MyModalLabel">Cart</h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Continue shopping</button>
        <a href="cart/index" type="button" class="btn btn-primary">Make order</a>
        <button type="button" class="btn btn-danger" onclick="clearCart()">Clear Cart</button>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Casino math testing", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">


        <li><%= link_to "Dashboard",   select_path %></li>



          <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile" %></li>
                  <li><%= link_to "Settings", edit_user_registration_path %></li>

                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
                  </li>
                </ul>
              </li>

            <li><%= link_to "Log in", user_session_path %></li>

          </ul>
        </nav>
      </div>
    </header>

app/views/static_pages/black_jack.html.erb
<h2>Black Jack Test</h2>

<table class="bj-table" action="" tabindex="0" method="post">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Ante</th>
      <th scope="col">Pay</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td><%= a = rand(11..199)*5 %></td>
      <td><input type="text" name="rezult"></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td><%= rand(11..199)*5 %></td>
      <td><input type="text" name="rezult"></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td><%= rand(11..199)*5 %></td>
      <td><input type="text" name="rezult"></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td><%= rand(11..199)*5 %></td>
      <td><input type="text" name="rezult"></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">5</th>
      <td><%= rand(11..199)*5 %></td>
      <td><input type="text" name="rezult"></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">6</th>
      <td><%= rand(11..199)*5 %></td>
      <td><input type="text" name="rezult"></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">7</th>
      <td><%= rand(11..199)*5 %></td>
      <td><input type="text" name="rezult"></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">8</th>
      <td><%= rand(11..199)*5 %></td>
      <td><input type="text" name="rezult"></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">9</th>
      <td><%= rand(11..199)*5 %></td>
      <td><input type="text" name="rezult"></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">10</th>
      <td><%= rand(11..199)*5 %></td>
      <td><input type="text" name="rezult"></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row"></th>
      <td></td>
      <td><input type="submit" class="btn btn-success" onSubmit="return check(this);"></td>
    </tr>
  </tbody>
</table><br><br>

<script type="text/javascript">
  function check(form){
for (var i=0; i < table.rezult.length; i++)
{
	if (table.rezult[i]) return true;
}
alert ("Please check for one of the available options");
return false;
}
</script>

app/views/static_pages/select.html.erb
<ul>
  <li><%= link_to "Russian poker", russian_poker_path, class: "btn btn-lg btn-primary" %></li><br>
  <li><%= link_to "Roulette", roulette_path, class: "btn btn-lg btn-primary" %></li><br>
  <li><%= link_to "Texas holdem poker", texas_holdem_path, class: "btn btn-lg btn-primary" %></li><br>
  <li><%= link_to "Black jack", black_jack_path, class: "btn btn-lg btn-primary" %></li><br>
  <li><%= link_to "Bacarratt", bacarratt_path, class: "btn btn-lg btn-primary" %></li><br>
  <li><%= link_to "Complites", complites_path, class: "btn btn-lg btn-primary" %></li><br>
</ul>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>